set nocompatible

syntax enable
filetype plugin on

" FINDING FILES
set path+=** " two stars (**) means search through the directories recursively
set wildmenu " gives me a display of possible files if there are multiple
set wildmode=longest:full,full

" Browser tweaks
let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

